// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD95p5ckkGFB-jLSlx3C3Ic-ws10s3oQEs',
    appId: '1:421092657942:web:84c58c0cad3afa71e3de37',
    messagingSenderId: '421092657942',
    projectId: 'vehicle-parts-store',
    authDomain: 'vehicle-parts-store.firebaseapp.com',
    storageBucket: 'vehicle-parts-store.firebasestorage.app',
    measurementId: 'G-M74VDN1J1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTbEQl2XxT_fBVDQBOUMmmmNkFvyRr_qc',
    appId: '1:421092657942:android:8a052df073c74500e3de37',
    messagingSenderId: '421092657942',
    projectId: 'vehicle-parts-store',
    storageBucket: 'vehicle-parts-store.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD95p5ckkGFB-jLSlx3C3Ic-ws10s3oQEs',
    appId: '1:421092657942:web:9d02c1a5a430b0a7e3de37',
    messagingSenderId: '421092657942',
    projectId: 'vehicle-parts-store',
    authDomain: 'vehicle-parts-store.firebaseapp.com',
    storageBucket: 'vehicle-parts-store.firebasestorage.app',
    measurementId: 'G-3RLX088D4X',
  );
}
